= 文档属性

每个文档头部都可以设置一系列键值对，它们称为文档属性。文档属性可以用于控制 AsciiDoc 处理器的行为，声明文档元数据，或者定义可重用的内容。

文档属性的作用域是文档级别，意味着在 A 文档中定义的文档属性不会影响 B 文档，也不能被 B 文档使用。

AsciiDoc 语言中内置了一些文档属性，同样也允许我们或扩展定义额外的文档属性，在允许的情况下还能够替换内置的属性。

内置属性不仅提供了关于文档和环境的只读信息，也允许我们配置 AsciiDoc 处理器在处理整个文档或特定区域时的行为。

.以下是文档属性的一些用途：
* 提供文档相关信息
* 定义文档元数据
* 打开或关闭处理器的功能特性
* 声明资源的位置（如：图片）
* 存储文档中需要重用的内容

== 文档属性的类型

文档属性分为两种：内建属性和自定义属性。

=== 内建属性

内建属性可以用于控制文档中的常见特性，许多文档属性只有定义在文档头时才生效。
布尔属性是内建属性中的一种，如果一个布尔属性被定义了，但是没有给它设置值，那么它默认是开启状态，如果属性没有定义，那么就是关闭状态，它们扮演的是一个开关的角色。

=== 用户自定义属性

当我们的文档中出现了太多重复的文本，或者某些文本经常需要变动的时候，可以考虑使用自定义属性。

自定义属性的主要用法是将频繁使用的文本和 URLs 提升到文档顶部。

定义自定义属性：

[,asciidoc]
----
:disclaimer: Don't pet the wild Wolpertingers. If you let them into your system, we're \
not responsible for any loss of hair, chocolate, or purple socks.
:url-repo: https://github.com/asciidoctor/asciidoctor
----

属性值过长时，可以使用行延续符（空格 + 反斜杠）将一行分隔到多行。

之后，我们就可以在文档中引用这些属性了。 

== 定义文档属性的注意事项

文档属性的值可以没有（因为内建的属性有默认值），也可以是 AsciiDoc 中的内联值，但不能是块内容，如列表、多段落等。

== 怎么取消设置一个文档属性

可以在文档头部或文档体中通过在属性名前面或后面添加惊叹号（!）将属性取消设置。

=== 在文档头将文档属性取消设置

在文档头将一个属性取消设置时不需要提供属性值，且必须独占一行。下面是两种形式（惊叹号分别添加在属性名前后）的取消属性设置的示例：

[,asciidoc]
----
= Title
:!name:
:name!:
----

NOTE: 将惊叹号添加在属性名的前面是更推荐的方式。

接下来通过一个名为 `sectids` 的内建属性演示怎么将内建属性取消设置，该属性的作用是为每个章节标题生成一个 ID。`sectids` 属性在处理阶段被 ASciiDoc 处理器自动设置，除非我们手动取消设置。

[,asciidoc]
----
= Document Title
:!sectids:
----

=== 在文档体中将属性取消设置

自定义属性和一些内建属性可以在文档体中取消设置。例如，假设我们在文档头部设置了章节编号属性 `sectnums`，但是文档中间的两个标题我们不想要编号，那么我们可以在第一个想要取消编号的标题前面将章节标题编号属性 `sectnums` 取消设置，当我们想要后续的章节标题被继续编号时，可以重新设置该属性：

[,asciidoc]
----
= Title
:sectnums:

== Section Title

:!sectnums:
== Section Title

=== Section Title

:sectnums:
== Section Title
----

== 文档属性可以定义在哪

* 定义在文档头部
* 定义在文档体
* 通过 API 选项设置（`:attributes`）
* 通过 CLI 选项设置（`-a`）

== 怎么引用一个文档属性

使用语法 `{attribute-name}` 可以引用文档属性，意味着在引用处，对应的属性名会被该属性定义的值替换。

文档属性可以在文档中任何可以应用属性替换的地方引用，即，属性引用可以在属性条目的值、标题、段落文本、列表文本、元素属性的值以及宏的目标上使用。

[NOTE]
文档属性需要先定义后才能引用。
