= 属性条目（Attribute Entries）

在文档中使用文档属性之前，我们需要先声明文档属性。属性条目是在 AsciiDoc 文档中定义文档属性的主要机制。可以将属性条目看做是文档的全局变量赋值，文档属性在定义之后即可在后续文档中使用，但是注意不能在定义属性之前引用它。

== 属性条目的定义

一个属性条目由两部分组成：一个属性名和一个属性值。属性名位于首位，后面则跟随一个可选的值。每个属性都必须独占一行。同时，属性名需要由冒号（:）包裹起来。

.下面是一个不带属性值的文档属性声明：
[,asciidoc]
----
:name-of-an-attribute:
----

.许多时候需要给文档属性赋值：
[,asciidoc]
----
:name-of-an-attribute: value of the attribute
----

[NOTE]
需要注意属性值跟属性名的闭合冒号之间必须至少有一个空格

== 定义一个属性时引用其它的属性

在定义一个属性条目时，我们可以在属性值部分引用其它已定义的属性，属性条目的值部分对属性的引用是被立即解析的。

[,asciidoc]
----
:url-org: https://example.org/projects
:url-project: {url-org}/project-name
----

== 布尔属性或有默认值的属性

一些内建的属性不需要赋值，因为它们是布尔属性（功能开关）或有默认值。

.没有赋值的属性会在 AsciiDoc 处理器处理时推断它的值：
[,asciidoc]
----
:name-of-an-attribute:
----

== 属性条目的定义位置

属性条目经常定义在文档头部，也可以在文档体中的块之间定义。

[WARNING]
属性条目不能在分割块的内部定义。

当属性定义在文档头部的时候，称为头部属性（Header attribute），头部属性在整个文档中都是可用的，直到手动将其取消设置。

当属性定义在文档体中时，可以简单将其称为文档属性，定义该属性之后即可在文档中使用，直到手动将其取消设置。正文中定义的属性无法通过文档元数据获取。

除非属性被锁定，否则它可以在文档头或文档体中被取消设置或分配一个新值。需要注意的是，在文档体中取消设置或重定义一个控制行为的头部属性通常不会生效。

== 在文档外部定义属性

如果不想在文档中定义属性，也可以通过 API 或 CLI 声明文档属性，API 和 CLI 都提供了自己独特的属性声明方式，API 使用 `:attributes` 选项声明，CLI 使用 `-a` 选项。

当在文档外部声明属性时，它的值不会发生替换，同样也意味着，当在文档内部对文档外定义的属性进行引用时，文档外定义的属性的值中的特殊字符和引用同样不会被替换，但是宏替换则依然生效。

当从 CLI 或 API 定义一个属性时，该属性会隐式地称为一个文档头属性，默认情况下属性是被锁定的，意味着不能被取消设置，所以不能从文档内部对其进行修改，不过这个行为可以通过在属性名或值的后面添加 @ 符号改变。唯一的例外是 `sectnums` 属性，它总是可以被修改的。

== 自定义属性名规范

用户自定义的属性名不能是 AsciiDoc 中内建的属性名，且需要符合以下规则：
* 至少一个字符的长度
* 以小写字母、数字或下划线开头
* 仅包含小写字母、数字、下划线和连字符（-）
* 不能包含点和空格

虽然大写字母也是允许的，但是处理时会被转化成小写字母，因此最好是只使用小写字母

== 属性值的类型和分配方法

属性值可以是字符串（包含空字符串）或者数字，这取决于属性。如果属性接收一个字符串值，字符串中可能会包含对其它属性的引用和内联宏。注意属性值不能包含复杂的多行块元素如表格或侧边栏。

内建属性的值接受什么类型主要取决于属性，而用户定义属性的值只接受字符串类型。

分配方法 :: 
属性值的分配方法可分为自动分配和必须由用户手动分配，支持哪一种主要由属性决定，如果一个属性有它的默认值，那么如果用户没有手动分配，则处理器会自动选取属性的默认值。当一个属性没有默认值时，用户必须手动赋值。

内建值 :: 
许多内建属性有一个或多个内建值，这些值中的某一个可以作为属性的默认值，当你没有给属性设置值时 AsciiDoc 处理器将会使用这个默认值。

处理器在处理时会自动设置多个内建的属性的默认值，除非你显式地取消设置或者给它们赋值。
