= 内建的文档属性
:built-in-attr: 内建属性（Built-in Attributes）

ASciiDoc 处理器有一些为了特殊意图保留的属性，称为{built-in-attr}，内建属性可以添加、配置或控制文档中的一些常见的特性，许多{built-in-attr}只有在文档头部使用属性条目形式定义时才会生效。

== 使用属性的默认值

许多内建属性有默认值，当你想要启用对应的属性且使用它的默认值的时候，可以不提供属性条目的值。

例如，对于 `toc` 属性，可以这样做：

[,asciidoc]
----
= Title of Document
:toc:
----

因为 `toc` 属性有默认值（`auto`），因此上述示例中我们没有提供属性值，在该属性被处理时，它的默认值会被自动分配。

== 覆盖属性默认值

有时我们不希望使用属性的默认值，此时可以给属性设置一个值以覆盖它的默认值。前提是没有通过 CLI 或 API 将这个属性进行锁定（因为锁定的属性无法对其进行修改）。

如 `doctype` 内建属性，它的默认值是 `article`，但我们希望将其改为 `book`，可以这样做：

[,asciidoc]
----
= Title of My Document
:doctype: book
----

NOTE: 属性值跟闭合冒号（:）之间必须至少有一个空格。

=== 覆盖资源目录的默认值

有一些资源目录相关的内建属性用于定义资源的存放位置，且它们都有默认值，如果我们的资源没有按照默认位置存放，就需要手动修改这些属性的值。如：图片目录（默认是空）、图标目录（默认是 `.images/icons`）、层叠样式表目录（默认是`.stylesheets`）和 JavaScript 文件目录（默认是 `./javascripts`）等。

修改资源目录属性的默认值：

[,asciidoc]
----
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: .js
----

== 布尔属性

布尔属性是扮演开关角色的{built-in-attr}，它唯一的功能是打开某种功能或行为。

布尔属性可以在文档头部或文档体中设置，布尔属性的值总是空字符串。当一个属性被设置，且它的值为空时，它的值会被解释为 `true`，而当一个属性没有被设置时，值会被解释为 `false`。当然，当属性值为 `true` 时，处理器也会将其解释为布尔值 `true`。

ASciiDoc 中有个名为 `sectanchors` 的布尔属性，用于开启章节标题前的锚点标识（当鼠标放到标题上时展示）：

[,asciidoc]
----
:sectanchors:
----
