= 文档属性分配优先级

== 默认属性值优先级

属性分配优先级从高到底依次为：

1. 使用 CLI 或 API 定义的属性
2. 文档中定义的属性
3. 属性的默认值（如果有的话）

以 `imagesdir` 属性来说，它的默认值是空字符串，如果我们不给该属性分配值（不管是通过 CLI 还是 API），处理器将为其分配默认值空字符串。如果在文档中分配了值，则该值将覆盖默认值；最后，如果又通过 API 或 CLI 为该属性分配了值，则该值将覆盖文档中分配的值和默认值。

== 改变属性值分配优先级

通过在属性值的末尾或属性名末尾添加 @ 优先级修饰符，可以修改默认的属性值分配优先级，*@ 修饰符用于降低分配优先级，这种形式称为“软设置”*。

NOTE: 在进行分配前，@ 修饰符会被删除。

现在假设我们在文档中已经定义了 `imagesdir` 属性的值：

[,asciidoc]
----
= Document Title
:imagesdir: new/path/to/images
----

此时如果我们在 CLI 中还给该属性分配值，那么默认情况下 CLI 中分配的值会是该属性最终的值，但是有时候这不是我们想要的，此时可以在 CLI 中使用修饰符 @ 将 CLI 中分配的值的优先级降低。

在 CLI 中，通过在属性值后面添加修饰符改变分配优先级：

[,bash]
----
asciidoctor -a imagesdir=images@ doc.adoc
----

我们也可以将修饰符添加在属性名的后面：

[,bash]
----
asciidoctor -a imagesdir@=images doc.adoc
----

两种形式效果都是一样的，现在虽然我们在 CLI 中也给该属性分配了值，但是因为在 CLI 中使用修饰符降低了 CLI 值分配的优先级，因此最终该属性的值会是文档中指定的。

如果要从 CLI 或 API 软取消设置一个属性，可以使用这种语法：

[,asciidoc]
----
!name=@
----

前导的惊叹号（!）用于将属性取消设置，而 @ 则降低分配优先级。

我们重新梳理下使用优先级修饰符后的分配优先级列表：

1. 传递给 CLI 或 API 的属性值，不使用 @ 修饰符
2. 文档中定义的属性
3. 传递给 CLI 或 API 的属性值，使用 @ 修饰符
4. 属性的默认值（如果有）
