= 文档头
yokura <yokura05@gmail.com>
:description: 文档头相关知识介绍

文档头包含文档标题、作者和修订信息或其它文档元数据，文档头是可选的。

== 文档头结构

文档头是文档开头的一系列连续的行，如果文档有标题，则文档标题必须被放在除空行和注释之外的第一行。

IMPORTANT: 文档头结束的标志是空行，空行标志着文档头的结束和文档正文的开始。

文档头通常以文档标题开头，指定文档标题后，后面可以紧跟着（不能有空行，空行标志着文档头结束）一行或多行指定的内容，比如，作者信息和修订信息。

文档头可以包含以下信息：

* 可选的文档标题（0 级标题）
* 文档作者和修订信息
* 可选的文档属性和元数据，包括内置和用户定义的
* 可选的注释行

文档头的常见元素：

[source,asciidoc,linenums]
----
// this comment line is ignored
= Document Title
Kismet R. Lee <kismet@asciidoctor.org>
:description: The document's description.
:sectanchors:
:url-repo: https://my-git-repo.com

The document body starts here.
----

接下来逐行解释：

1. 注释行，会被忽略
2. 文档标题
3. 作者信息
4. 给内置的文档属性分配元数据
5. 设置内置的文档属性
6. 用户自定义的文档属性
7. 一行空行，用于将文档头跟正文分隔
8. 文档正文

其实文档属性可以放置在文档头中的任何位置，包括文档标题的上方，但是推荐放在文档标题下方。其次，因为文档标题是可选的，因此文档头可能只由文档属性组成。

== 不同文档类型对文档头的要求

当文档类型 `doctype` 为 `article` 或 `book` 时，文档头是可选的，而当文档类型为 `manpage` 时，文档头是必需的。

== 文档头处理

当将 AsciiDoc 文档转换为独立文档时，默认显示文档头的信息，如果不想这样，可以在文档头或 CLI 中设置 `noheader` 属性规避。

== 前言

许多静态网站生成器（Jekyll 和 Middleman）都依赖文档顶部的前言决定如何转换内容，Asciidoctor 有许多属性可用于正确处理前置内容。
